services:
  lms-config:
    container_name: lms-config
    image: lms/config:0.0.1
    ports:
      - 8888:8888
    networks:
      - spring-microservices-network

#  mysql-user:
#    image: mysql:8.0
#    container_name: mysql-user
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: users_db
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    ports:
#      - "3307:3306"
#    networks:
#      - spring-microservices-network
#    volumes:
#      - mysql-user-data:/var/lib/mysql

#  keycloak:
#    container_name: keykloak-ms
#    image: quay.io/keycloak/keycloak:24.0.2
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HEALTH_ENABLED: "true"
#    command:
#      - start-dev
#    ports:
#      - "9098:8080"
#    networks:
#      - spring-microservices-network
#    restart: always

  lms-discovery:
    container_name: lms-discovery
    image: lms/discovery:0.0.1
    ports:
      - "8761:8761"
    networks:
      - spring-microservices-network
    depends_on:
      - lms-config

#  lms-user:
#    container_name: lms-user
#    image: lms/user:0.0.1
#    ports:
#      - "8090:8090"
#    networks:
#      - spring-microservices-network
#    restart: always
#    depends_on:
#      - lms-config
#      - mysql-user
#      - lms-discovery
#
#  lms-gateway:
#    container_name: lms-gateway
#    image: lms/gateway:0.0.1
#    ports:
#      - "8222:8222"
#    networks:
#      - spring-microservices-network
#    depends_on:
#      - lms-config
#      - mysql-user
#      - lms-discovery
#      - lms-user

networks:
  spring-microservices-network:
    driver: bridge

volumes:
  mysql-user-data:
